/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kjnthrxztjcoonjvypcj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqbnRocnh6dGpjb29uanZ5cGNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NDg1ODYsImV4cCI6MjA3NjMyNDU4Nn0.ctoc3RiLC-E7_0DzNIcx3_cwj2r9GehSlIJjO-VN-ug"
